// <auto-generated />
using ItroducereDateCuptor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ItroducereDateCuptor.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20191205090949_AddNewDataToModel")]
    partial class AddNewDataToModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ItroducereDateCuptor.Blum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calitate")
                        .HasMaxLength(10);

                    b.Property<string>("DataOraLaminare");

                    b.Property<int>("Diametru");

                    b.Property<string>("Furnizor")
                        .HasMaxLength(2);

                    b.Property<bool>("IsDatAfara");

                    b.Property<bool>("IsRebut");

                    b.Property<bool>("IsRetur");

                    b.Property<int>("Lungime");

                    b.Property<string>("Normalizare")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Sarja")
                        .HasMaxLength(8);

                    b.Property<string>("Sectiune");

                    b.HasKey("Id");

                    b.ToTable("Blums");
                });
#pragma warning restore 612, 618
        }
    }
}
